runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /$
  static_files: index.html
  upload: index.html

- url: /osk$
  script: osk.application

- url: /((css|font|img|js).*)
  static_files: \1
  upload: (css|font|img|js).*
